language: node_js

addons:
  postgresql: "9.3"
  apt:
    sources:
        - ubuntu-toolchain-r-test
    packages:
        - g++-4.8

node_js:
    - '4.2'

services:
    - postgresql

before_install:
    - export CXX="g++-4.8"

before_script:
    - npm install juttle@^0.5.0;

script:
    - npm run test-coverage
    - npm run check-coverage
