language: node_js

addons:
  postgresql: "9.3"
  apt:
    sources:
        - ubuntu-toolchain-r-test
    packages:
        - g++-4.8

before_install:
    - export CXX="g++-4.8"
    - npm install juttle@>=0.4.0

node_js:
    - '4.2'
    - '5.0'

services:
  - postgresql

before_script:
    - npm install -g jshint
    - npm install -g jscs

script:
    - npm run -s lint
    - npm test
